name = "HomotopyContinuationGym"
uuid = "5820fc11-79f2-4cda-9342-3a97ef075eee"
license = "MIT"
repo = "https://github.com/JuliaHomotopyContinuation/HomotopyContinuationGym.jl.git"
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PolynomialTestSystems = "4c526841-e1e8-562c-bfa9-9f39d642e243"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
HomotopyContinuation = "^1"
julia = "^1.1"
